//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tottos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuadrecaja
    {
        public int id { get; set; }
        public Nullable<int> idCuadre { get; set; }
        public decimal efectivo { get; set; }
        public decimal visa { get; set; }
        public decimal egreso { get; set; }
        public decimal caja { get; set; }
    
        public virtual cuadre cuadre { get; set; }
    }
}
