//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tottos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public formulario()
        {
            this.formulaiorolpermiso = new HashSet<formulaiorolpermiso>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idmenu { get; set; }
        public string nombremenu { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<sbyte> activo { get; set; }
        public Nullable<sbyte> visible { get; set; }
        public string icon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formulaiorolpermiso> formulaiorolpermiso { get; set; }
        public virtual menu menu { get; set; }
    }
}
