//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tottos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remuneraciones
    {
        public int id { get; set; }
        public int idPersonal { get; set; }
        public int aniopago { get; set; }
        public int mespago { get; set; }
        public System.DateTime dia { get; set; }
        public string concepto { get; set; }
        public decimal importe { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
